[package]
org = "ballerinax"
name = "netsuite"
version = "0.9.8"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-netsuite"
keywords = ["NetSuite", "Finance", "Integration"]
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
