[package]
distribution = "2201.3.0"
org = "ballerinax"
name = "netsuite"
version = "3.0.1"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-netsuite"
keywords = ["Business Management/ERP", "Cost/Paid"]
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
