name: CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action@slbeta6
              with:
                  args:
                      pack ./netsuite
            - name: Ballerina Test
              uses: ballerina-platform/ballerina-action@slbeta6
              with:
                  args:
                      test ./netsuite
              env:
                  NS_BASE_URL: ${{ secrets.BASEURL }}
                  NS_TOKEN_SECRET: ${{ secrets.TOKENSECRET }}
                  NS_TOKEN: ${{ secrets.TOKEN }}
                  NS_CLIENT_ID: ${{ secrets.CONSUMERID }}
                  NS_CLIENT_SECRET: ${{ secrets.CONSUMERSECRET }}
                  NS_ACCOUNTID: ${{secrets.ACCOUNTID}}
                  
